name: Dependency review

on:
  workflow_call:
    inputs:
      fail-on-provenance-change:
        description: 'Fail the workflow if provenance changes are detected'
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Check provenance downgrades
        uses: danielroe/provenance-action@41bcc969e579d9e29af08ba44fcbfdf95cee6e6c # v0.1.1
        with:
          fail-on-provenance-change: ${{ inputs.fail-on-provenance-change }}

      - name: Dependency review
        if: github.event.pull_request || github.event.merge_group
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        with:
          base-ref: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
          head-ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
